services:
  web:
    image: serverpr-web:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/Data/db.sqlite3
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
